import json
from pathlib import Path

print("\n" + "="*80)
print("RESUMO EXECUTIVO: VIABILIDADE ST-GCN PARA PREVISÃO DE CVLI")
print("="*80)

# Carregar dados
with open("teste_modelo/01_apenas_ocorrencias/metadata_analise_1_CORRIGIDA.json") as f:
    m1 = json.load(f)
with open("teste_modelo/02_ocorrencias_prisoes/metadata_analise_2_CORRIGIDA.json") as f:
    m2 = json.load(f)
with open("teste_modelo/03_relatorio_comparativo/summary_comparativo.json") as f:
    summary = json.load(f)

print(f"\n📊 DADOS ANALISADOS")
print(f"   Período: {m1['periodo']}")
print(f"   Total dias: {m1['total_dias']}")
print(f"   Bairros normalizados: {m1['total_bairros']}")
print(f"   Eventos CVLI: {m1['eventos_cvli']:,}")

print(f"\n📈 RESULTADOS")
print(f"\n   ANÁLISE 1 - CVLI-only")
print(f"   {'-'*50}")
print(f"   Tensor: {m1['total_dias']} dias × {m1['total_bairros']} bairros = {m1['tensor_cells']:,} células")
print(f"   Células com evento: {m1['cells_nonzero']:,} ({(m1['cells_nonzero']/m1['tensor_cells']*100):.2f}%)")
print(f"   Esparsidade: {m1['sparsity']*100:.2f}%")
print(f"   Sinal médio: {m1['signal_nz_mean']:.4f} eventos/dia/bairro")
print(f"   Variabilidade (CV): {m1['cv']:.3f}")
print(f"")
print(f"   Score: {'█'*19}░ {m1['score']['geral']:.1f}/100")
print(f"   Status: ✅ VIÁVEL (Score >= 60)")

print(f"\n   ANÁLISE 2 - CVLI + Contexto (Prisões + Apreensões)")
print(f"   {'-'*50}")
print(f"   Features: 3 (CVLI + Prisões + Apreensões)")
print(f"   Tensor: {m2['total_dias']} dias × {m2['total_bairros']} bairros × 3 features")
print(f"   Eventos CVLI: {m2['eventos_cvli']:,}")
print(f"   Eventos Prisões: {m2['eventos_prisoes']:,}")
print(f"   Eventos Apreensões: {m2['eventos_apreensoes']:,}")
print(f"")
print(f"   Correlação CVLI↔Prisões: {m2['correlacoes']['cvli_prisoes']:.3f} (fraca)")
print(f"   Correlação CVLI↔Apreensões: {m2['correlacoes']['cvli_apreensoes']:.3f} (muito fraca)")
print(f"")
print(f"   Score: {'█'*19}░ {m2['score']['geral']:.1f}/100")
print(f"   Status: ✅ VIÁVEL (Score >= 60)")

print(f"\n🏆 RECOMENDAÇÃO FINAL")
print(f"   {'-'*50}")
print(f"   {summary['recomendacao']}")
print(f"   {summary['razao']}")
print(f"")
print(f"   Diferença de scores: {summary['diferenca']:+.1f} ({summary['diferenca_pct']:+.1f}%)")
print(f"   Conclusão: Ambas abordagens são praticamente equivalentes")
print(f"")
print(f"   ➜ Para MVP: Use ANÁLISE 1 (mais simples)")
print(f"   ➜ Para Produção: Use ANÁLISE 2 (com contexto operacional)")

print(f"\n📁 ARTEFATOS GERADOS")
print(f"   Análise 1: teste_modelo/01_apenas_ocorrencias/")
print(f"      ✓ tensor_cvli_only_CORRIGIDO.npy")
print(f"      ✓ RELATORIO_ANALISE_1_CORRIGIDA.md")
print(f"      ✓ metadata_analise_1_CORRIGIDA.json")
print(f"")
print(f"   Análise 2: teste_modelo/02_ocorrencias_prisoes/")
print(f"      ✓ tensor_cvli_prisoes_CORRIGIDO.npy")
print(f"      ✓ RELATORIO_ANALISE_2_CORRIGIDA.md")
print(f"      ✓ metadata_analise_2_CORRIGIDA.json")
print(f"")
print(f"   Comparativo: teste_modelo/03_relatorio_comparativo/")
print(f"      ✓ RELATORIO_COMPARATIVO_FINAL.md")
print(f"      ✓ summary_comparativo.json")

print(f"\n{'='*80}")
print(f"✅ ANÁLISE CONCLUÍDA - PRONTO PARA IMPLEMENTAÇÃO DE ST-GCN")
print(f"{'='*80}\n")
